### ISSUE TITLE
Displayed author name does not include parenthesized comment text

### ISSUE THREAD

**Issue by dagolden** [metacpan/metacpan-web#1479]
Some authors have clarifying comments in their 01mailrc address.  This is particularly important for deceased authors, who are shown like "John Doe (PAUSE Custodial Account)".

search.cpan.org displays the full text and metacpan.org should as well.

**Comment by oalders** [comment]
Example author name: AMORETTE

http://api.metacpan.org/author/AMORETTE

```
{
   "email" : [
      "amorette@cpan.org"
   ],
   "name" : "Hojung Youn",
   "pauseid" : "AMORETTE",
   "country" : "KR",
   "website" : [],
   "gravatar_url" : "https://secure.gravatar.com/avatar/7f265acaa082d74fd03320dce955acbf?s=130&d=identicon",
   "user" : "Cu9dkkDuQ1ytr9LceAtlVg",
   "dir" : "id/A/AM/AMORETTE",
   "profile" : [
      {
         "name" : "twitter",
         "id" : "am0c"
      },
      {
         "id" : "am0c",
         "name" : "github"
      }
   ],
   "updated" : "2012-12-20T05:32:22",
   "city" : "Seoul"
}
```

**Comment by oalders** [comment]
Do we add another field here or just stop stripping away the data inside of parentheses?  @rwstauner? @haarg ?

**Comment by haarg** [comment]
I don't believe we are stripping this information.  Example:
https://metacpan.org/author/NI-S
https://api.metacpan.org/author/NI-S

We don't seem to be updating our data from 00whois sometimes.  I do notice that AMORETTE has profiles linked, so they must have logged on to MetaCPAN.

**Comment by rwstauner** [comment]
This issue has caused confusion several times.  What we probably should do
is keep "00whois" data separate from profile overridden data.

Even if we kept a timestamp with each source, it's not necessarily easy to
say which should have precedence (for example, if ETHER wants her "look of
disapproval" to show on metacpan, but doesn't put that in PAUSE, just
because something at PAUSE changed doesn't mean we should undo her metacpan
change), but it would be the beginnings of allowing us to merge the data
for display.

I doubt there would be (too many) objections if metacpan would diff the
profile name from the PAUSE name, and show both if they differ (or better
yet, show the part that is different (in this case the parenthetical)).

**Comment by oalders** [comment]
> This issue has caused confusion several times.  What we probably should do
is keep "00whois" data separate from profile overridden data.

I was thinking the same thing.  Actually, we could do this for various PAUSE files.  I've got a branch that handles `06perms`.  We could add `02packages` and `00whois` as well.

**Comment by ranguard** [comment]
Closing in favour of https://github.com/metacpan/metacpan-api/issues/621
