### ISSUE TITLE
Missing cache control headers

### ISSUE THREAD

**Issue by dolmen** [metacpan/metacpan-web#1522]
A new release of Test::CPAN::Meta appeared today with an updated POD, but Firefox still shows me the page it fetched 2 days ago (same browser session).
It appears that no cache control headers have been received with the page 2 days ago.
Here is the request/response as it is exported with the Live HTTP Headers extension.

```
GET /pod/Test::CPAN::Meta HTTP/1.1
Host: metacpan.org
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
DNT: 1
Referer: https://metacpan.org/search?q=Test%3A%3ACPAN%3A%3AMeta
Cookie: metacpan_secure=<hidden>
Connection: keep-alive

HTTP/1.1 200 OK
Server: nginx/1.6.2
Content-Type: text/html; charset=utf-8
Last-Modified: Tue, 13 Jan 2015 02:05:45 GMT
X-Runtime: 0.433169
Content-Encoding: gzip
Via: 1.1 varnish, 1.1 varnish
Accept-Ranges: bytes
Date: Tue, 05 May 2015 08:44:39 GMT
Age: 0
X-Served-By: cache-lcy1123-LCY, cache-ord1720-ORD
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
Vary: Accept-Encoding, Cookie
```

Cc: @ilmari

**Comment by ranguard** [comment]
So, yes, currently we don't return cache headers for browsers... (we also have our CDN, Fastly, set to not cache anything at the moment, hence the X-Cache: MISS stuff, but I'm actively working on improving this, first by moving customisation, logged in status and favs, in to JS/AJAX rather than the returned HTML)...

Out of interest, what caching would you expect... e,g, how long should we tell a browser and/or proxy to cache something? - 5 mins, an hour, a day?...

Eventually the CDN will have a massive cache TTL, but we will purge when the content changes, so a lower browser TTL wouldn't have such a hit on our servers

**Comment by dolmen** [comment]
I do not expect more than one release per day for a distribution, so one day for caching would be ok.
I'm keeping my browser open for weeks.

**Comment by haarg** [comment]
Related #1765

**Comment by ranguard** [comment]
We now set a 1 hour browser cache header
