### ISSUE TITLE
Missing module: EekBoek

### ISSUE THREAD

**Issue by sciurius** [metacpan/metacpan-web#1657]
EekBoek is on CPAN, is in the CPAN 02packages.details.txt and not a POD-only module.
However, it is missing on the author's page (mine) and in the metacpan search.

**Comment by oalders** [comment]
I re-indexed it manually this morning.  It's here: https://metacpan.org/release/JV/EekBoek-2.02.05  It has a status of "cpan" rather than "latest".  `02packages` says;

` EekBoek                         2.02.05  J/JV/JV/EekBoek-2.02.05.tar.gz`

`06perms` says `EekBoek,JV,f`

API info here: https://explorer.metacpan.org/?url=%2Frelease%2FJV%2FEekBoek-2.02.05

I'm not sure what's going on.  @rwstauner, thoughts?

**Comment by rwstauner** [comment]
Does the indexer print any messages?
My first observation is that the meta has "lib" under "no_index" which
seems like it wouldn't be helpful.
I'm not sure what the indexer (or PAUSE) will do with that though.

**Comment by sciurius** [comment]
This is the indexer report.

The following report has been written by the PAUSE namespace indexer.
Please contact modules@perl.org if there are any open questions.

  User: JV ()
  Distribution file: EekBoek-2.02.05.tar.gz
  Number of files: 336
  *.pm files: 102
  README: EekBoek-2.02.05/README
  META-File: EekBoek-2.02.05/META.yml
  META-Parser: Parse::CPAN::Meta 1.4414
  META-driven index: yes
  Timestamp of file: Tue Mar  8 07:29:15 2016 UTC
  Time of this run: Tue Mar  8 07:30:46 2016 UTC

Status of this distro: OK
=========================

The following packages (grouped by status) have been found in the distro:

Status: Successfully indexed
============================

     module : EekBoek
     version: 2.02.05
     in file: lib/EekBoek.pm
     status : indexed

__END__

**Comment by sciurius** [comment]
The reason for the "noindex lib" is to prevent all the application private modules (that absolutely make no sense individually) from being indexed. This was suggested many years ago by the PAUSE/CPAN team.

**Comment by oalders** [comment]
The MetaCPAN indexer doesn't complain and it says that the distribution contains one module.

**Comment by rwstauner** [comment]
There's nothing in metacpan's "provides" array, though...

**Comment by neilb** [comment]
@sciurius I notice that your no_index says the following:

    no_index:
      directory:
        - inc
        - lib

That is saying to not index anything in the lib directory, which is where EekBoek.pm is.
Instead of this, I think you to use `no_index file` on `lib/EB.pm`, and then `no_index directory` on `inc` and `lib/EB`. That should leave lib/EekBoek.pm indexed.

I'm not 100% sure of this, but given the definition of `no_index`, it would explain why nothing is being indexed by MetaCPAN.

**Comment by sciurius** [comment]
It is reasonable to expect 'provides' (explicit inclusion) to override 'no_index'.

In any case, the MetaCPAN behaviour differs from the historically correct CPAN.

**Comment by neilb** [comment]
@sciurius the spec for this ([CPAN::Meta::Spec](https://metacpan.org/pod/CPAN::Meta::Spec)) isn't clear on this point, and there's an [open issue](https://github.com/Perl-Toolchain-Gang/CPAN-Meta/issues/43) on that point.

**Comment by haarg** [comment]
Related: #849

**Comment by oalders** [comment]
Closing as @neilb's suggestion for handling `no_index` would fix this.
