### ISSUE TITLE
Add a "Contributing" link in the left sidebar if the dist has a Contributing file

### ISSUE THREAD

**Issue by neilb** [metacpan/metacpan-web#1779]
To encourage people to read the Contributing file (and add them to their own dists :-), how about adding a link in the left sidebar (near Changes and Homepage)?

**Comment by Tux** [comment]
+10!

**Comment by neilb** [comment]
Wow, don't think I've ever got a +10 before \o/

**Comment by oalders** [comment]
This one is so easy, that I'll even do it myself.

**Comment by neilb** [comment]
> This one is so easy, that I'll even do it myself.

+4.2!

**Comment by oalders** [comment]
This _should_ already work.  https://github.com/metacpan/metacpan-web/blob/master/lib/MetaCPAN/Web/Model/API/Release.pm#L322

Can you point me to a module with a `Contributing` file where this isn't being displayed?

**Comment by neilb** [comment]
@oalders from a quick glance at that code, that seems to be decided what to show in the main body of the page?

I was suggesting linking it in the left sidebar, where Changes, Repository, etc get listed.

For an example, look at [Dist::Zilla::Plugin::Deprecated](https://metacpan.org/pod/Dist::Zilla::Plugin::Deprecated)

**Comment by zakame** [comment]
Looking into doing this now, I take that @neilb wanted something like this?

![image](https://user-images.githubusercontent.com/110625/39082691-b663f79e-4589-11e8-9b05-e6955a21cce4.png)

**Comment by oalders** [comment]
@zakame yes, that would be perfect. :)

**Comment by zakame** [comment]
@oalders thanks!  It seems that the UI change is simple, but the way to get Contributing link is something else; I know I can get it from `API::Release->interesting_files()`, but that seems excessive since I'd get a list every time (and also the method seems to be called only for `/release/` pages on web, while this particular link would show on both `/pod/$module` and `/release/$release`.)

Would it make sense to make a new API call here, say `/release/contributing_doc/$author/$release`?  I took a look at API and such a call might function like the one for fetching release Changes (and also it can check on multiple candidates like `CONTRIBUTING`, `CONTRIBUTING.md` `HACKING`, etc.)

**Comment by zakame** [comment]
@oalders yep, I saw the "Other Files" section on the Release page, which takes its info from the above-mentioned `API::Release->interesting_files` method.

I already got a somewhat-working implementation of an API call, mostly cribbed from looking at how release/distribution Changes are found (c.f. https://github.com/metacpan/metacpan-api/blob/master/lib/MetaCPAN/Document/File/Set.pm#L611.)  I also considered linking to `Contributing.pod`/`HACKING.pod` files as there are quite a few dists that ship with this format; will be posting initial commits for these in a bit...

**Comment by icklekitten** [comment]
Would be nice if this link was hidden for distributions which don't have a contributing file.

**Comment by zakame** [comment]
Thanks @icklekitten, feel free to contribute a PR to implement this.  I suspect this just needs some form of predicate function, which can then be used in toggling https://github.com/metacpan/metacpan-web/pull/2042/files#diff-749c885511d70923c53d03cd5916255bR9.
