### ISSUE TITLE
My module was uploaded on CPAN but it's not showing on MetaCPAN

### ISSUE THREAD

**Issue by pavelsr** [metacpan/metacpan-web#1789]
First time faced with such situation. What's wrong?

Name of my module is [Telegram::BotKit](http://search.cpan.org/~pavelsr/Telegram-BotKit-0.01/)

http://search.cpan.org/~pavelsr/
https://metacpan.org/author/PAVELSR

**Comment by oalders** [comment]
@pavelsr this module does not appear in `02packages.details.txt`.  It's here on MetaCPAN https://metacpan.org/release/PAVELSR/Telegram-BotKit-0.01

You'll need to find out why PAUSE didn't index it.  Did you get an email from PAUSE?  It _might_ be because there's no actual `Telegram::BotKit` in your dist.

**Comment by Grinnz** [comment]
This seems resolved

**Comment by oalders** [comment]
@Grinnz thanks!
