### ISSUE TITLE
MooseX::Declare & class declarations does not seem to be indexed (such modules are absent from search results or author listings)

### ISSUE THREAD

**Issue by burak** [metacpan/metacpan-web#1920]
https://metacpan.org/release/PSILVA/App-PortDistances-0.0.1

vs

http://search.cpan.org/~psilva/App-PortDistances-0.0.1/lib/App/PortDistances/DB.pm

Note that metacpan does not even list it in the search results. I assume the latter indexes the distribution name and makes it available

The only section where one can locate such things is the "All releases by this author" page like:  https://metacpan.org/author/PSILVA/releases

**Comment by haarg** [comment]
We only include modules in the search results if they are indexed by PAUSE and included in the 02packages file.  This dist isn't indexed there due to the MooseX::Declare syntax.

We are handling it a bit strangely though.  The module documentation should be available even if the dist isn't included in search results.

**Comment by haarg** [comment]
The module documentation is available now, so I'm considering this fixed.
