### ISSUE TITLE
The back button is getting corrupted on the Firefox browser

### ISSUE THREAD

**Issue by benkasminbullock** [metacpan/metacpan-web#1980]
There is some sort of error where the back button gets corrupted when using Firefox.

Steps to reproduce:

1. Go to https://metacpan.org/release/Image-SVG-Path
2. Click on the "examples" like "Home_for_the_aged.svg"
3. After arriving at the example page, click the back button on the browser.

This should take one back to the original page, but it doesn't, unless the back button is clicked twice.

I tested this with the Chrome browser but was not able to reproduce it, so it seems to only affect Firefox. Similarly, Microsoft Edge did not display the problem.

**Comment by haarg** [comment]
There are two issues here.  First is that a link fragment is getting added in places where it shouldn't be, so the file has an erroneous `#PHome_for_the_aged.svg` fragment.  I have a fix for that I'll apply soon.  Second is that the link fragment gets changed when loading the source page.  This is intentional, but I don't think it is a good idea.  The link targeting code should be adjusted to not change the fragment.
