### ISSUE TITLE
File::Spec Requirement Too High

### ISSUE THREAD

**Issue by theory** [metacpan/metacpan-web#2026]
The [File::Spec requirement](https://metacpan.org/source/MITHALDU/PPI-1.236/META.yml#L32) is for v3.2701, but the [highest released version](https://metacpan.org/pod/File::Spec) is v3.74. There is a [v3.2701](https://metacpan.org/pod/release/KWILLIAMS/PathTools-3.2701/lib/File/Spec.pm), which is unfortunate. I mean, these File::Spec versions are bonkers! Any chance it could require a somewhat more recent version with a saner short version? 3.28 perhaps?

**Comment by haarg** [comment]
The requirement is for 3.2701, not v3.2701.  And 3.2701 is less than 3.74.  If this is a problem for you, then whatever code you are using is interpreting perl versions incorrectly.

Also, this is filed on the wrong bug tracker.  This is the metacpan-web issue tracker, not the [PPI issue tracker](https://github.com/adamkennedy/PPI/issues).

**Comment by shadowcat-mst** [comment]
Generally once you use a certain number of digits for the post-dot part of a version, it's considered polite to maintain at least that number of digits until the next major version, specifically because some packaging systems don't realise that plain perl versions are decimal rather than two-part.

Ideally, File::Spec would keep to this approach and 3.74 would instead be 3.7400, but alas it appears the maintainer chose otherwise.

**Comment by theory** [comment]
Sorry, don't know how I put it on the metacpan issue tracker. Weird.

What mst is my understanding, too, but that ship done sunk on File::Spec *years* ago.
