### ISSUE TITLE
How to show correct documentation for executable script in bin directory?

### ISSUE THREAD

**Issue by hakonhagland** [metacpan/metacpan-web#2181]
The [`csvgrep`](https://metacpan.org/release/NEILB/csvgrep-0.07) distribution contains no modules, but has a single script also called [`csvgrep`](https://st.aticpan.org/source/NEILB/csvgrep-0.07/bin/csvgrep) in the `bin` folder. There is a dummy module [`csvgrep.pm`](https://st.aticpan.org/source/NEILB/csvgrep-0.07/lib/csvgrep.pm) in the `lib` folder. The problem is that this module does not contain the documentation for the script. The real documentation is in the script in the bin folder. When a user searches for `csvgrep` on metacpan.org he will end up with the page with no documentation. What is the best way to solve this issue?

The user is supposed to find this page:

   https://metacpan.org/pod/release/NEILB/csvgrep-0.07/bin/csvgrep

but it is not so easy to find from the metacpan.org UI.

**Comment by Grinnz** [comment]
The easiest way would probably be to rename the module to App::csvgrep (as is convention) so that the module does not take precedence for documentation. Another way would just be to duplicate the documentation to the module (something Dist::Zilla could possibly take care of).

**Comment by oalders** [comment]
Ping @neilb

**Comment by Grinnz** [comment]
Another option would be to change the NAME heading for csvgrep.pm or just remove all the POD from it. Then metacpan won't index it as documentation for that module.

**Comment by hakonhagland** [comment]
@Grinnz Thanks for the suggestions! Renaming the module might be the best approach in the long term (so it agrees with the convention). But removing all POD from `csvgrep.pm` also might be the simplest.

**Comment by hakonhagland** [comment]
Added [pull request](https://github.com/neilb/csvgrep/pull/15).

**Comment by neilb** [comment]
In the first release I just included the script. But it didn't get indexed by PAUSE, because PAUSE ignores things in the `bin` directory. You can see in the [Changes](https://metacpan.org/source/NEILB/csvgrep-0.07/Changes) file that I quickly did another release, adding the module to make PAUSE happy.

I'm guessing I could add `provides` in the metadata, so PAUSE wouldn't need the module. Then I could drop the module. Would be nice to test that theory first with a developer release, but PAUSE doesn't index developer releases.

I'm busy with work stuff for the next week or so, but if someone wants to do a PR for this, I'd give it a go :-)

**Comment by neilb** [comment]
@Grinnz pointed out on IRC that my hack would have meant that cpanm wouldn't know how to check the version to see whether an upgrade was needed. So I went with his suggestion and Håkon's PR.

Thanks both!

**Comment by oalders** [comment]
Looks much better. Thanks @hakonhagland, @Grinnz and @neilb!
