### ISSUE TITLE
metacpan changing the name of a file in the distribution listing

### ISSUE THREAD

**Issue by brainbuz** [metacpan/metacpan-web#2207]
In Vote::Count there is a file "Hand_Count.pod", metacpan is listing it in the distribution as Hand.

under =head1 NAME it is Hand_Count_Methods

it had been "Hand Count Methods" without underscores I made that change hoping it would help.

[Hand_Count.pod.txt](https://github.com/metacpan/metacpan-web/files/3567004/Hand_Count.pod.txt)

**Comment by Grinnz** [comment]
It appears to show up as Hand_Count_Methods in https://metacpan.org/release/BRAINBUZ/Vote-Count-0.02410-TRIAL.

**Comment by brainbuz** [comment]
It still shouldn't be necessary to add the underscores. 

And yes I also confused myself because distzilla ignored a --trial command line flag for a testing release and 0.2401 is really a backtrack to 0.22. I did figure out why it did that (stable/unstable in dist.ini is taking precedence over the flag).

**Comment by Grinnz** [comment]
The format of the NAME section is subject to both metacpan and man page pickiness, as described at https://perldoc.pl/perlpodstyle#NAME1. Programs and module names both generally don't contain spaces so that's why it wouldn't be recognized here.

**Comment by brainbuz** [comment]
I think I'm the edge case here with a distribution that is documentation heavy, that has topic documentation pages that aren't module specific. So I'm closing this issue and living with underscores as a work around.
I had to choose whether to build a documentation site for the distribution or use metacpan or github as the primary documentation site, I think metacpan is the best choice (and it implicitly promotes perl), but I have to live with the limitations it imposes.

**Comment by Grinnz** [comment]
Tangentially related, consider namespacing your documentation's file path even if it's not module specific, as otherwise EUMM may install it in a location not related to your distribution's name (which at least would be vaguely "owned" by your distribution). This path where it ends up is also what users would need to pass to perldoc to open the documentation locally. In the current location it will get installed to Vote::Hand_Count for example and this is just legacy EUMM behavior, it may be simpler to organize it explicitly in lib/.
