### ISSUE TITLE
Suggestion: Add ClickHeat or Mouseflow

### ISSUE THREAD

**Issue by djzort** [metacpan/metacpan-web#2225]
ClickHeat is foss, and mouseflow is paid. Either provide a heatmap of how people use the site. This information helps understand what people are finding useful versus what is just taking up space.

There may be other options, i mention these two only as examples.

**Comment by haarg** [comment]
I don't really see what value this would provide that we couldn't get from log analytics.  MetaCPAN doesn't really have much for interactive elements.

**Comment by djzort** [comment]
The purpose is to guide design revisions to improve accessibility based upon hard data as to what is being used and what isnt. The heat map visualization is helpful for humans in interpretation.

**Comment by oalders** [comment]
I think this is great, but the hard reality is that nobody is currently working to improve accessibility.  The front end design has been mostly ignored for years since it mostly works and we have thornier problems to solve.  We are very short on people power, so even if we had the data, it's likely nobody would check it or turn it into actionable items. Are you offering to work on this?  :)

**Comment by djzort** [comment]
My intention was to socialize the idea first and see what people's feedback is. The comments thus far have been the sort of information i was hoping to receive.

**Comment by oalders** [comment]
Closing for now.  If someone comes along who wants to take this on and maintain it, we can revisit this.
