### ISSUE TITLE
Fix / document indexing bundled exeutables (using App::Cmd / etc.)

### ISSUE THREAD

**Issue by shlomif** [metacpan/metacpan-web#2347]
Hi all! countdown appears here: https://metacpan.org/release/App-Countdown (has a link to https://metacpan.org/pod/distribution/App-Countdown/bin/countdown ) whereas timestamper does not appear here: https://metacpan.org/release/App-Timestamper . How can it be fixed?

**Comment by oalders** [comment]
Hi @shlomif! Have a look at the `NAME` section: https://metacpan.org/release/App-Timestamper/source/bin/timestamper#L14-16

You'll see that in the case of `/bin/countdown`, you're using a name of `countdown` in the Pod. 

For `bin/timestamper`, it is actually being linked in the `Documentation` section of the release page, but the page is using the `NAME` section from your Pod rather than the file name.

Hope this helps!

**Comment by shlomif** [comment]
Thanks @oalders ! I submitted a new release now with the fix.

**Comment by oalders** [comment]
Thanks @shlomif! I will close this issue then.
