### ISSUE TITLE
Files in "t2" directories probably shouldn't show up in "Other files"

### ISSUE THREAD

**Issue by tobyink** [metacpan/metacpan-web#2405]
Files in "t2" are test cases which are intended to run under the Test2 framework. (Test2 does also run files in "t" of course.)

They are currently showing up in the "Other files" section:
https://metacpan.org/release/Test2-Harness

**Comment by tobyink** [comment]
Hmm, it looks that distribution includes quite a lot of files in "t2":
https://metacpan.org/source/EXODIST/Test2-Harness-1.000036/t2

But only "t2/exception.t" shows up in the "Other files" section.

**Comment by oalders** [comment]
@exodist is this a convention we should be taking into account?

**Comment by haarg** [comment]
This file is showing up because files or paths starting with `ex` are [treated as examples](https://github.com/metacpan/metacpan-api/blob/master/lib/MetaCPAN/Query/File.pm#L144-L154). `t`, `xt`, and several other directories [are excluded](https://github.com/metacpan/metacpan-api/blob/master/lib/MetaCPAN/Query/File.pm#L274-L275). It would be trivial to add `t2` to that list.

**Comment by exodist** [comment]
yeah, t2/ should get the same treatment as t/ if that's easy enough to do. Specifically t2 is a directory where yath looks for tests but prove does not. It is a way to designate them as yath-only tests (yath being the Test2 based harness). In the Test2-Harness dist specifically it is where there are tests that check that yath set specific yath-only env-variables, and similar things.

**Comment by shadowcat-mst** [comment]
@exodist why ... would you do that ... surely you could test for a RUNNING_UNDER_YATH type env var in those tests?

This doesn't seem like a general feature that anybody else would want, and the harness can handle it that way, so ... this seems like a single dist special case which doesn't seem to have a lot of point

**Comment by exodist** [comment]
@shadowcat-mst I can do without the drama right now, your words imply I shot your political candidate and did it just to spite you.

The situation came about organically starting when I was first prototyping yath before I knew I would release it, or that anyone would use it. I was trying to quickly test that yath did some things so I wrote scripts that verified things got done. At the time yath did not have a way to set env vars (or do much of anything frankly) but I needed the scripts that became the current yath-only tests not to be run when I used prove to run the real tests (cause yath was not yet able to). So I shoved them in t2/ for convenience. At the time yath was not even smart enough to understand a skip-all, so even if it did set an env var there was no easy way to use it.

By the time yath was stable and released about 3 years later that dir was formalized into tests, but the many tests were not updated to work outside yath or skip if not run by yath. Since nothing else cared about t2/ I felt no need to engage in the effort to fix that. As for documentation/encouragement of the feature, all I have done is document that yath will also search t2/ for tests by default. I have not documented that people should write yath-only tests, nor encouraged people to do it in t2/. The only sane reason I can think of for someone to write yath-only tests in a t2/ directory would be if they are working on yath, or a yath plugin/extension.

**Comment by tobyink** [comment]
Currently the distributions that I've been able to identify using a t2 directory are:

- Test2-Harness
- Business-OnlinePayment-BankOfAmerica
- Business-OnlinePayment-StGeorge

And that's all. It doesn't seem as widespread as I thought it might be.

**Comment by exodist** [comment]
I just took a look at Business-OnlinePayment-BankOfAmerica  last release was in 2002, so its t2/ dir is unrelated to yath, which was still years away as 2002 is about the time I started learning perl.

**Comment by Grinnz** [comment]
My feeling would be we should hold off special casing this dir until and unless it becomes a recommended practice.

**Comment by oalders** [comment]
Based on the above, I don't think we need to special case this directory. Thanks everyone!
