### ISSUE TITLE
Use gravatar instead of person icon when user is logged in

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-web#2757]
<img width="335" alt="Screen Shot 2022-09-30 at 13 27 55" src="https://user-images.githubusercontent.com/96205/193324695-5e869826-9343-4ed5-975a-0299d43376f8.png">

Right now the icon turns from black to red after login, which is helpful, but it actually wasn't obvious to me that I was still logged in, because to know this I have to remember the logged-out colour of the icon.

It would be nice to use a gravatar (like GitHub does) to give a clear visual indicator that some is currently logged in.

**Comment by dhogan8** [comment]
@oalders How does the following look?

<img width="1511" alt="Screen Shot 2022-10-01 at 9 16 15 AM" src="https://user-images.githubusercontent.com/52248962/193411373-3810fb53-5c5c-46b4-bd70-4093c3292087.png">
<img width="1512" alt="Screen Shot 2022-10-01 at 9 15 40 AM" src="https://user-images.githubusercontent.com/52248962/193411377-220651ad-6bf2-4a6e-8af9-ba2dfea741ed.png">
<img width="815" alt="Screen Shot 2022-10-01 at 9 16 09 AM" src="https://user-images.githubusercontent.com/52248962/193411375-3cd67025-9058-46c6-9228-5c222262d374.png">
<img width="813" alt="Screen Shot 2022-10-01 at 9 15 49 AM" src="https://user-images.githubusercontent.com/52248962/193411376-428a0a63-e538-46d8-af23-c8990df459fd.png">

**Comment by oalders** [comment]
That looks great!

**Comment by dhogan8** [comment]
Great! I added this to this PR: https://github.com/metacpan/metacpan-web/pull/2759. I'm just struggling a bit with this issue: https://github.com/metacpan/metacpan-web/pull/2759#discussion_r985102751. If it might not be an easy fix to do, I can create a separate PR.

I mainly included this issue and https://github.com/metacpan/metacpan-web/issues/2749 in the same PR since they both touch the navbar icons / buttons.

**Comment by oalders** [comment]
Closing as this has been addressed #2761, #2763 and #2766.
