### ISSUE TITLE
Broken "PR #" links in list of changes

### ISSUE THREAD

**Issue by esabol** [metacpan/metacpan-web#3141]
The links to `PR #33` and `PR #35` on this web page are both broken (404s):

https://metacpan.org/release/MANWAR/Test-Strict-0.53

The `PR #33` link to http://github.com/manwar/Test-Strict/33 obviously should be going to http://github.com/manwar/Test-Strict/pull/33 instead.

The Changes file in this distribution doesn't have links for `PR #33` and `PR #35` in it, so I presume it is MetaCPAN which is adding these links in its HTML render.

**Comment by esabol** [comment]
Also, I just noticed that the links are "http" and not "https"? Is that intentional? I suggest changing your GitHub links to "https" unless you really care about every byte of bandwidth. :smile:

**Comment by haarg** [comment]
Fixed by #3148

This impacted dists using GitHub as their issue tracker, but not if they only specified a repository. Which is probably why it wasn't noticed until now.

The http links are because Test::Strict uses http links in its metadata. My PR just reconstructs the URLs, so it will use https even if the metadata does not.

**Comment by esabol** [comment]
> Fixed by #3148

Has #3148 been deployed to metacpan.org yet? Because I'm not seeing it fixed there. Also, the string "pull" does not appear in the changes to #3148. I only see "Issues".

**Comment by esabol** [comment]
@haarg : Please re-open this issue. It is _not_ fixed.
